name: Playwright Tests

on:
  push:
    branches:
      - dev2
  workflow_dispatch:
    inputs:
      testTag:
        description: Select the type of tests to run
        required: true
        type: choice
        default: sanity
        options:
          - sanity
          - smoke
          - e2e
      confirm:
        description: "Type 'confirm' to proceed with the deployment"
        required: true
        default: ""

jobs:
  setup-shard:
    runs-on: ubuntu-latest
    outputs:
      shard-index: '${{ steps.set-shard-index.outputs.shardIndex }}'
      testFile: '${{ steps.set-shard-index.outputs.testFile }}'
    steps:
      - name: Validate Confirmation
        run: |
          if [ "${{ inputs.confirm }}" != "confirm" ]; then
            echo "Deployment canceled: Confirmation not provided."
            exit 1
          fi
      
      - name: Set shardIndex and testFile based on testTag
        id: set-shard-index
        run: |
          if [[ "${{ github.event.inputs.testTag }}" == "smoke" ]]; then
            echo "::set-output name=shardIndex::[1,2,3]"
            echo "::set-output name=testFile::smoke.yml"
          elif [[ "${{ github.event.inputs.testTag }}" == "e2e" ]]; then
            echo "::set-output name=shardIndex::[1]"
            
